### ISSUE TITLE
Add contributing.md

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/analog-clock#2]

**Comment by Santhusha-bit** [comment]
Can I work on this?

**Comment by RachitGarg-12** [comment]
Hey @Santhusha-bit  , I would like to work on this issue.

**Comment by Santhusha-bit** [comment]
@Sanket1308 You can assign this to him

**Comment by AdarshCoder397** [comment]
Hey @Sanket1308 , I can work on this!

**Comment by Mayank1170** [comment]
Hey @Sanket1308 i'll already work on the projects like this, can you please assign this issue to me so that i can fix it.

**Comment by Sanket1308** [comment]
@AdarshCoder397 and @Mayank1170, thanks for your interest!

@Mayank1170 , we're assigning issues on a first come first serve basis. If @AdarshCoder397  isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue [here](https://github.com/Sanket1308?tab=repositories).

**Comment by AdarshCoder397** [comment]
Hey @Mayank1170 , You can work on this ! Have a great exposure by doing contribution in hacktoberfest !! Contribute well
