### ISSUE TITLE
Footer section

### ISSUE THREAD

**Issue by Geetisha17** [boradesanket13/analog-clock#25]

**Comment by yashB-2002** [comment]
I would like to work on this issue, Please assign it to me.

**Comment by Sanket1308** [comment]
@Geetisha17 Please specify your approach before starting to the coding

@yashB-2002 thanks for your interest!
We're assigning issues on a first come first serve basis. If @Geetisha17  isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue [here](https://github.com/Sanket1308?tab=repositories).

**Comment by Geetisha17** [comment]
@Sanket1308 I'm thinking of adding current year and a redirect link to your github profile.

**Comment by Geetisha17** [comment]
@Sanket1308 I'm thinking of adding current year and a redirect link to your github profile in the footer section.

**Comment by Sanket1308** [comment]
Go ahead!

**Comment by Sanket1308** [comment]
Doesn't look good... Just add a producthunt button at lower left
