### ISSUE TITLE
want to add a random quote at bottom of clock

### ISSUE THREAD

**Issue by yasaswini999** [boradesanket13/analog-clock#26]
@Sanket1308 pls assign me this issue

**Comment by Sanket1308** [comment]
Great idea @yasaswini999! Can you tell me how will you implement it?

**Comment by sid172014** [comment]
@Sanket1308 hey , we can have a ton of quotes stored in a JSON file then with the help of JS we’ll randomly fetch those quotes , I can work on this , please consider assigning ..

**Comment by yasaswini999** [comment]
@sid172014 storing all details in a JSON file will make us create another js file
but I would like to fetch the data by API  available online which results in a few lines of code
BTW the code is working on my local machine. @Sanket1308
so I was thinking to raise a PR @Sanket1308 What do you think??

**Comment by Sanket1308** [comment]
Fetching quotes from an API will be better way to do it! Go for it, @yasaswini999 🚀

@sid172014, thanks for your interest!
We're assigning issues on a first come first serve basis. If @yasaswini999  isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue [here](https://github.com/Sanket1308?tab=repositories).

**Comment by yasaswini999** [comment]
@Sanket1308 pls check my PR  #31
