### ISSUE TITLE
Change numbers color in dark mode to black.

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/analog-clock#27]

**Comment by abel-otegbola** [comment]
Hi @Sanket1308  can you assign this to me

**Comment by JatinSingh08** [comment]
Hey @Sanket1308 , assign this to me please....I've contribute to your repo previously also.

**Comment by abel-otegbola** [comment]
Please @Sanket1308 this is a very nice project. I'd really love to contribute to it.

**Comment by Geetisha17** [comment]
hey @Sanket1308 I would love to work on this project can you assign me this.

**Comment by Sanket1308** [comment]
@abel-otegbola @Geetisha17 and @JatinSingh08 , thanks for your interest!

@Geetisha17 and @JatinSingh08 , we're assigning issues on a first come first serve basis. If @abel-otegbola  isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue [here](https://github.com/Sanket1308?tab=repositories).
