### ISSUE TITLE
Take the dark mode toggle to upper right side.

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/analog-clock#34]
![Screenshot (1116)](https://user-images.githubusercontent.com/79108273/194745494-ca67e40c-fa03-4bcc-8cd2-ad5244ae8fe9.png)

**Comment by ShishuSidharth** [comment]
please assign this to me

**Comment by RachitGarg-12** [comment]
@Sanket1308 please assign this to me

**Comment by boradesanket13** [comment]
@RachitGarg-12 and @ShishuSidharth , thanks for your interest!

@RachitGarg-12 , we're assigning issues on a first come first serve basis. If @ShishuSidharth  isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue [here](https://github.com/Sanket1308?tab=repositories).
