### ISSUE TITLE
Add a footer with linkedIn and github logo

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/analog-clock#35]

**Comment by zainbinfurqan** [comment]
Can i work on it please

**Comment by S-Parker7000** [comment]
I am on it

**Comment by S-Parker7000** [comment]
@zainbinfurqan I am just making the PR please search different issue

**Comment by Sanket1308** [comment]
@zainbinfurqan and @S-Parker7000 , thanks for your interest!
Assigning this issue to @zainbinfurqan!
@S-Parker7000 , we're assigning issues on a first come first serve basis. If @zainbinfurqan  isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue [here](https://github.com/Sanket1308?tab=repositories).

**Comment by sahilsharma029** [comment]
Hello! @Sanket1308 
can you please assign me this issue?
I want to work on it.

**Comment by Sanket1308** [comment]
@sahilsharma029 , thanks for your interest!

@sahilsharma029 , we're assigning issues on a first come first serve basis. If @zainbinfurqan  isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue [here](https://github.com/Sanket1308?tab=repositories).

**Comment by ABHAY-Y** [comment]
Sir, can you assign this task to me?
