### ISSUE TITLE
Adding date on left Conner 

### ISSUE THREAD

**Issue by lusifer65** [boradesanket13/analog-clock#50]
if we are adding date on left Conner is looking great

**Comment by lusifer65** [comment]
@Sanket1308  can you assign to me for work ?

**Comment by ABHAY-Y** [comment]
Sir, can you assign this task to me?

**Comment by boradesanket13** [comment]
@lusifer65 Date wont look good in an analog clock. But if really wanna work on this. You can add another page for digital clock.

**Comment by boradesanket13** [comment]
@ABHAY-Y, thanks for your interest!

We're assigning issues on a first come first serve basis. If @lusifer65  isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue [here](https://github.com/Sanket1308?tab=repositories).

**Comment by pranavajith** [comment]
Hey @boradesanket13 
Would you mind assigning me this issue? I've never done something like this before..

**Comment by AnkitGurwan** [comment]
@boradesanket13 , I can help in adding date in the page.

**Comment by ankushj0801** [comment]
I would like to work on this. Please assign it to me

**Comment by boradesanket13** [comment]
@pranavajith Go for it
@ankushj0801 @AnkitGurwan we are assigning on FCFS basis
