### ISSUE TITLE
Take the socials toggle to right side

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/analog-clock#52]

**Comment by devika-singh** [comment]
Can I be assigned this issue?

**Comment by Gaurav945572** [comment]
Please assign me this task

**Comment by iamatifmoin** [comment]
@boradesanket13 
I have resolved the issue. Please review the PR.

**Comment by SattyamSamania** [comment]
Hey @boradesanket13 If the issue is still open can I work on this?

**Comment by boradesanket13** [comment]
> @boradesanket13 I have resolved the issue. Please review the PR.


Thanks for your interest! Get issues assigned before writing code from next time.  Happy Hacking!🚀
