### ISSUE TITLE
Centre align the quotes

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/analog-clock#53]

**Comment by devika-singh** [comment]
Hey ... can I be assigned this?

**Comment by devika-singh** [comment]
I did a pull request for the same please review it?

**Comment by devika-singh** [comment]
Yeah sorry about that I thougth coding period started

**Comment by pranavajith** [comment]
Hey @boradesanket13 
Could you assign me this issue?

**Comment by ankushj0801** [comment]
I would like to work on this please assign it to me

**Comment by sankooru14** [comment]
@boradesanket13 Please assign this issue to me

**Comment by Abhijeet-2003** [comment]
I would like to work on this @boradesanket13

**Comment by Abhijeet-2003** [comment]
if the issue is still open, please assign it to me. @boradesanket13
