### ISSUE TITLE
Add jokes instead of quotes

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/analog-clock#54]

**Comment by boradesanket13** [comment]
Use API for data

**Comment by MysteryHawk17** [comment]
Please assign me this issue to contribute to it under Codepeak 2022.

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀

**Comment by MysteryHawk17** [comment]
Thank you .
And I should make a PR after or on 5th right..?

**Comment by pranavajith** [comment]
Should this issue remain unsolved, I'd like to take it up afterwards, @boradesanket13 . It really intrigues me.
