### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/analog-clock#55]

**Comment by DarK-VEnOM-16** [comment]
@boradesanket13  can you assign this issue to me for work ?

**Comment by pranavajith** [comment]
@boradesanket13 I'd like to take this one up please.

**Comment by boradesanket13** [comment]
@pranavajith , we're assigning issues on a first come first serve basis. If @DarK-VEnOM-16  isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another codepeak issue [here](https://github.com/boradesanket13?tab=repositories).
