### ISSUE TITLE
Improve CONTRIBUTING.md

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/analog-clock#56]

**Comment by pranavajith** [comment]
@boradesanket13 Could you assign me this issue please.

**Comment by SattyamSamania** [comment]
Hey @boradesanket13 I would like to work on this issue. Please tell further what to do next.

**Comment by pranavajith** [comment]
> @boradesanket13 Could you assign me this issue please.

@boradesanket13 it'd mean a lot if you could assign me this asap.

**Comment by boradesanket13** [comment]
> @boradesanket13 Could you assign me this issue please.

Complete preasssigned issues first

**Comment by SattyamSamania** [comment]
Hey @boradesanket13 Is there any changes required in the Contributing.md?
