### ISSUE TITLE
Add LEARN.md

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/analog-clock#57]
A LEARN.md file to provide step by step instructions, with text and/or media, on how to built this project from scratch.

**Comment by pranavajith** [comment]
I'd like to solve this issue and create a LEARN.md file.

**Comment by pranavajith** [comment]
Will do!
Before that, would be great if I could get some kind of insight into what all a learn.md should include necessarily.

**Comment by boradesanket13** [comment]
- Just a brief description of how and what things have been implemented.
- List all features 
- What one should learn in particular techstack

> Will do! Before that, would be great if I could get some kind of insight into what all a learn.md should include necessarily. @boradesanket13
