### ISSUE TITLE
Change background images

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/analog-clock#58]

**Comment by Ajeetesh2003** [comment]
Hey @boradesanket13 can you assign me this issue to contribute under Codepeak 22.

**Comment by pranavajith** [comment]
@boradesanket13 
I'd like to work on this issue.

**Comment by Gaurav945572** [comment]
please assign it to me

**Comment by thevermaashutosh** [comment]
Please assign me this task. I want to contribute in this project. I am familiar with the tech stack being used here. HTML, CSS, and JavaScript.

**Comment by AnkitGurwan** [comment]
@boradesanket13 I would like to work on the issue. Please assign it to me

**Comment by aryabasu17** [comment]
I want to contribute to the issue , i hope i could bring some changes to the issue

**Comment by Abhijeet-2003** [comment]
I want to work on this issue @boradesanket13. Could you please assign it to me?
