### ISSUE TITLE
Adding favicon

### ISSUE THREAD

**Issue by AyushTripathiIITP** [boradesanket13/analog-clock#61]
I noticed that you website did'nt have any favicon, Can you assign me this issue @boradesanket13

**Comment by mpatwa98** [comment]
I want to work on this.

**Comment by ankushj0801** [comment]
I want to work on this issue. please assign it to me

**Comment by boradesanket13** [comment]
@AyushTripathiIITP Complete preassigned issues first

**Comment by AyushTripathiIITP** [comment]
![image](https://user-images.githubusercontent.com/101452500/206187345-c649a474-764d-4252-bee6-2dd218862f66.png)
@boradesanket13 does it fit

**Comment by mpatwa98** [comment]
@boradesanket13 do you want icon to change on dark mode and light mode or just one icon? I searched for hours for dark and light mode but couldn't find any satisfactory. or if u want just one icon then how it should be? minimilistic or anything that fits good?
