### ISSUE TITLE
Bug Hamburger Menu not aliened Properly. 

### ISSUE THREAD

**Issue by Kumar-Ankit56** [boradesanket13/analog-clock#69]
After clicking on the Hamburger menu social media icons are not visible looking to fix it.

@boradesanket13 please allow me to fix it.

**Comment by boradesanket13** [comment]
Go ahead! Contribute well🚀

**Comment by Prasad-mutnale** [comment]
@boradesanket13 bro can you please assign me this issue ? i can solve it

**Comment by Prasad-mutnale** [comment]
@boradesanket13 bro can i place hamburger in top left ? otherwise suggest me where to place it
