### ISSUE TITLE
Correct length of the seconds clock

### ISSUE THREAD

**Issue by Tushar98644** [boradesanket13/analog-clock#77]
<img width="1440" alt="Screenshot 2022-12-23 at 8 22 50 PM" src="https://user-images.githubusercontent.com/107763774/209355400-b5d57a4f-1cbf-4dcc-99c6-4bb196132218.png">

rn it is overlapping the time digits....correct it to a suitable length

**Comment by boradesanket13** [comment]
[Not Req]
